<% select case Request.QueryString("sayfa")
case "anasayfa"
	Session("sayfa")="anasayfa"
case "ayarlar"
	Session("sayfa")="ayarlar"
case "subeler"
	Session("sayfa")="subeler"
case "haber"
	Session("sayfa")="haber"
case "haber_kat"
	Session("sayfa")="haber_kat"
case "sayfa"
	Session("sayfa")="sayfa"
case "yemek"
	Session("sayfa")="yemek"
case "banner"
	Session("sayfa")="banner"
case "guncel_bilgiler"
	Session("sayfa")="guncel_bilgiler"
case "aylik yemek ucretleri"
	Session("sayfa")="aylik yemek ucretleri"
case "yemek ucretleri"
	Session("sayfa")="yemek ucretleri"
case "maillist"
	Session("sayfa")="maillist"
case "anket"
	Session("sayfa")="anket"
case "sayac"
	Session("sayfa")="sayac"
case "defter"
	Session("sayfa")="defter"
case "kelimeler"
	Session("sayfa")="kelimeler"
case "saldiran"
	Session("sayfa")="saldiran"
case "duyurular"
	Session("sayfa")="duyurular"
case "hesap"
	Session("sayfa")="hesap"
case "blok"
	Session("sayfa")="blok"
case "video_kat"
	Session("sayfa")="video_kat"
case "video"
	Session("sayfa")="video"
case "formmail"
	Session("sayfa")="formmail"
case "galeri"
	Session("sayfa")="galeri"
case "rezervasyonlar"
	Session("sayfa")="rezervasyonlar"
case "album"
	Session("sayfa")="album"
case "memur_personel"
	Session("sayfa")="memur_personel"
case "isci_personel"
	Session("sayfa")="isci_personel"
case "proje_kat"
	Session("sayfa")="proje_kat"
case "projeler"
	Session("sayfa")="projeler"
case "emlak arsiv"
	Session("sayfa")="emlak arsiv"
case "emlak projeler"
	Session("sayfa")="emlak projeler"
case "emlak il listesi"
	Session("sayfa")="emlak il listesi"
case "etkinlik"
	Session("sayfa")="etkinlik"
case "misafirhane"
	Session("sayfa")="misafirhane"
case "misafirhane_aylik"
	Session("sayfa")="misafirhane_aylik"
end select %>

<% Response.Redirect("giris.asp") %>